<div class="modal fade" id="selectRepuesto">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" title="Cerrar">&times;</button>
                <h4 class="modal-title">Seleccionar repuesto</h4>
            </div>
            <div class="modal-body">
                <table class="table">
                    <tr>
                        <th>Id</th>
                        <th>Marca</th>
                        <th>Descripción</th>
                        <th>Precio unitario</th>
                        <th>Stock</th>
                        <th>Opciones</th>
                    </tr>
                    <?php for($i=0; $i<count($repuestos); $i++){ $rs = $repuestos[$i]; ?>
                    <tr>
                        <td><?php echo $rs['id_repuesto']; ?></td>
                        <td><?php echo $rs['marca']; ?></td>
                        <td><?php echo $rs['descripcion']; ?></td>
                        <td><?php echo $rs['precio_unitario']; ?></td>
                        <td><?php echo $rs['stock']; ?></td>
                        <td>
                            <input type="checkbox"  id="seleccionar" onclick="addNewRow(this);">
                        </td>
                    </tr>
                    <?php } ?>

                </table>
                
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <button type="submit" class="btn btn-default" data-dismiss="modal" title="Aceptar">Aceptar</button>
                </div>
            </div>
        </div>
    </div>
</div>