<div class="modal fade" id="editRepuesto">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar almacen</h4>
            </div>
            <div class="modal-body">
                <form id="formEditCliente" action="../controllers/almacen/editAlmacen.php" method="post">
                    <input type="hidden" name="id_repuesto" id="id_repuesto">
                    <div class="form-group">
                        <input class="form-control" type="text" name="marca" id="new_marca" required autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="descripcion" id="new_descripcion" required autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="precio_unitario" id="new_precio_unitario" required autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="number" name="new_stock" id="new_stock" required autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>