<div class="modal fade" id="nuevoRepuesto">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Nuevo almacen</h4>
            </div>
            <div class="modal-body">
                <form id="formNuevoRepuesto" action="../controllers/almacen/addAlmacen.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="text" name="marca" id="marca" required placeholder="Marca" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="descripcion" id="descripcion" required placeholder="Descripción" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="precio_unitario" id="precio_unitario" required placeholder="Precio unitario" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="number" name="stock" id="stock" required placeholder="Stock" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>