#Config server y crear db cotejamiento utf8_spanish_ci

#Roles
CREATE TABLE rol(
	id_rol INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	rol VARCHAR(55) NOT NULL,
	fecha_log TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

#Usuarios
CREATE TABLE usuario(
	id_usuario INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	cuenta VARCHAR(55) NOT NULL UNIQUE,
	clave VARCHAR(115) NOT NULL,
	id_rol INT UNSIGNED NOT NULL,
	fecha_log TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_rol) REFERENCES rol(id_rol) 
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

#Vehiculos
CREATE TABLE vehiculos(
	id_vehiculo INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	marca VARCHAR(115) NOT NULL,
	modelo VARCHAR(115) NOT NULL,
	placa VARCHAR(7) UNIQUE NOT NULL,
	anio VARCHAR(5) NOT NULL,
	fecha_log TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

#Clientes
CREATE TABLE clientes(
	id_cliente INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nombres VARCHAR(215) NOT NULL,
	apellidos VARCHAR(215) NOT NULL,
	correo VARCHAR(55) NOT NULL,
	razon_social VARCHAR(55) NOT NULL,
	telefono VARCHAR(55) NOT NULL,
	rif VARCHAR(55) NOT NULL,
	direccion VARCHAR(255) NOT NULL,
	fecha_log TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

#Repuestos
CREATE TABLE repuesto(
	id_repuesto INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	descripcion VARCHAR(255) NOT NULL,
	marca VARCHAR(115) NOT NULL,
	precio_unitario VARCHAR(115) NOT NULL,
	stock VARCHAR(55) NOT NULL,
	fecha_log TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

#Factura
CREATE TABLE factura(
	id_factura INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_vehiculo INT UNSIGNED NOT NULL REFERENCES vehiculos,
	id_usuario INT UNSIGNED NOT NULL REFERENCES usuario,
	id_cliente INT UNSIGNED NOT NULL,
	iva VARCHAR(15) NOT NULL,
	total VARCHAR(115) NOT NULL,
	razon_social TEXT NOT NULL,
	n_poliza TEXT NOT NULL,
	n_siniestro TEXT NOT NULL,
	fecha VARCHAR(25) NOT NULL,
	estado INT NOT NULL, -- 1 pagada, 2 no pagada, 3 anulado
	fecha_log TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) 
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

#Factura Repuestos
CREATE TABLE factura_repuesto(
	id_fac_repuesto INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_repuesto INT NOT NULL,
	id_factura INT NOT NULL,
	cantidad VARCHAR(115) NOT NULL,
	fecha_log TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

#Nota de entrega
CREATE TABLE nota_entrega(
	id_nota_entrega INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	cod_nota_entrega VARCHAR(5) NOT NULL,
	id_factura INT UNSIGNED NOT NULL,
	empresa_envio VARCHAR(255) NOT NULL,
	guia VARCHAR(115) NOT NULL,
	costo_envio VARCHAR(115) NOT NULL,
	estado INT NOT NULL, -- 1 enviado, 2 recibido, 3 devuelto, 4 extraviado
	fecha_envio VARCHAR(15) NOT NULL,
	fecha_log TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_factura) REFERENCES factura(id_factura) 
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;